### PR TITLE
Allow react 17 compatibility

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by MilllerTime** [comment]
Hi, can I ask why you're trying to use this library with React 17?

I appreciate that you submitted a PR for this, however since React supports pointer events out of the box since 16.4, this library is obsolete for newer versions of React. I don't recommend using it unless you're stuck with an older version of React. As such, I don't want to add React 17 as a `peerDependency` as it really is not a good match.

**Comment by nikolas** [comment]
react-pointable is a dependency of [react-pdf-highlighter](https://github.com/agentcooper/react-pdf-highlighter), which I'm using for a project, and I'm getting this error:

```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0-0 || ^16.0.0-0" from react-pointable@1.1.3
npm ERR! node_modules/react-pdf-highlighter/node_modules/react-pointable
npm ERR!   react-pointable@"^1.1.1" from react-pdf-highlighter@4.0.0
npm ERR!   node_modules/react-pdf-highlighter
npm ERR!     react-pdf-highlighter@"*" from the root project
```

**Comment by nikolas** [comment]
Oh, so react-pdf-highlighter actually plans to remove react-pointable, for the reason you point out: https://github.com/agentcooper/react-pdf-highlighter/issues/145

**Comment by MilllerTime** [comment]
Ok, that makes sense. Good to see `react-pdf-highlighter` is going to drop this dependency in newer versions. I assume they will roll that out just as quickly as they would incorporate a new version of this library. Does that solution work for you?

**Pull request closed without merging**
